management:
  endpoints:
    web:
      exposure:
        include:
          - refresh

#------------------------Server    --------------------------#
server:
  port: 50101
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  #------------------------Cloud    --------------------------#
  cloud:
    config:
      enabled: false
  #------------------------Security --------------------------#
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:50907/realms/PolarBookshop
  #------------------------Hot Reload--------------------------#
  devtools:
    livereload:
      port: 35731
    restart:
      quiet-period:
      poll-interval: 2s
#------------------------Profiles Management--------------------------#
  profiles:
    active:
      - testdata

#-----------------------Logging------------------------------#
logging:
  level:
    ROOT: INFO
    web: DEBUG
    dev:
      ubaid: TRACE
    org:
      springframework:
        retry: DEBUG
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){yellow} %clr([%file:%line]){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"


#-----------------------Application--------------------------#
polar:
  greeting: Welcome Home from default prop file
