
#------------------------Hot Reload--------------------------#
spring:
  devtools:
    livereload:
      port: 35731
    restart:
      quiet-period: 2000
      poll-interval: 3000

#-----------------------Logging------------------------------#
logging:
  level:
    dev:
      ubaid: TRACE
    org:
      springframework:
        web: DEBUG
  pattern:
    console: %clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%file:%line]){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}