spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      uri: http://localhost:50100
      request-connect-timeout: 5000 #ms
      request-read-timeout: 5000 #ms
      fail-fast: false
      retry:
        max-attempts: 2
        initial-interval: 2000
        max-interval: 5000
        multiplier: 1.3
  datasource:
    username: polardb
    password:
    url: jdbc:postgresql://localhost:5590/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5


logging:
  level:
    root: DEBUG
    org.springframework.security: INFO