spring:
  cloud:
    config:
      enabled: false
  datasource:
    username: polardb
    password:
    url: jdbc:postgresql://localhost:5590/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5