management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true

#------------------------Server    --------------------------#
server:
  port: 50101
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  #------------------------Cloud    --------------------------#
  cloud:
    config:
      enabled: false
  #------------------------Security --------------------------#
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://localhost:50907}/realms/PolarBookshop
  #------------------------Hot Reload--------------------------#
  devtools:
    livereload:
      port: 51101
    restart:
      poll-interval: 2s
      quiet-period: 1s
      enabled: true
#------------------------Profiles Management--------------------------#
  profiles:
    active:
      - testdata

#-----------------------Logging------------------------------#
logging:
  level:
    dev:
      ubaid: TRACE
#-----------------------Application--------------------------#
polar:
  greeting: Welcome Home from default prop file
