apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: ghcr.io/ubaid4j/catalog-service:0.0.3-snapshot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50101
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://catalog-postgres/polardb_catalog
            - name: SPRING_DATASOURCE_USERNAME
              value: catalog
            - name: SPRING_DATASOURCE_PASSWORD
              value: catalog
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
              # TODO Create a minimal reproducible sample and create issue in spring boot repo
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: AUTH_SERVER_URL
              value: "http://polar-keycloak"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
